### ISSUE TITLE
don’t ask people to change a file in the plugin bundle

### ISSUE THREAD

**Issue by schriftgestalt** [Mark2Mark/Show-Siblings#1]
read a custom file from ~/Library/Application Support/Glyphs/ or ~/Library/Application Support/Glyphs/Info otherwise the info is gone if the plugin is updated.

**Comment by Mark2Mark** [comment]
Sorry, I cannot follow entirely. Can you please specify a bit? No rush.

**Comment by schriftgestalt** [comment]
In the description you say that people should edit the `ShowSiblings.py`file. Ask them to put the file in ~/Library/Application Support/Glyphs/Info and read it from there.

**Comment by Mark2Mark** [comment]
Oh, very interesting. I was not aware of that. I am currently developing this very Plugin to be smarter by default, which will make the user’s customisation hopefully obsolete. But nevertheless it is nice to know that there is apparently that way to store these custom settings. Thanks!
