### ISSUE TITLE
no siblings shown anymore

### ISSUE THREAD

**Issue by Nevu** [Mark2Mark/Show-Siblings#2]
Hi,

this plugin seems not to work with Version 2.3b (837). No siblings shown anymore ...

**Comment by Mark2Mark** [comment]
Hi, fixed it. This Plugin will be majorly updated soon with a bunch of new features. keep checking in.

**Comment by jtanadi** [comment]
Hi Mark,
I'm also not seeing the option. Currently using Glyphs 2.2.2 (827).

**Comment by Mark2Mark** [comment]
Is this still an issue? It was shown on my issues page. I am confuesd, it says it was opened in January?!
