### ISSUE TITLE
Plug-in not working with Glyphs 2.2.2

### ISSUE THREAD

**Issue by jtanadi** [Mark2Mark/Show-Siblings#3]
Hi Mark,
I'm also not seeing the option in the View menu. Currently using the newest Glyphs (2.2.2 (827)). The same also for Show Kerning Groups.

Have the plug-ins just not been updated to the newest Glyphs app, or do I need to install something else before I install these plug-ins?

Thanks,
JT

**Comment by Mark2Mark** [comment]
Hi JT.

This _could_ be due to my Plugins being _too_ up to date, I am mainly working with the cutting edge versions (2.3+). Even though I try to keep some downwards compatibility, it is hard to tell what still might work.

Would it be possible for you, to check your Mac Console for the named Plugins and report, what the console says for each of them? In this case I can trace back the issue.

Thanks for letting me know!
best, Mark

**Comment by jtanadi** [comment]
Thanks for getting back to me! This is what the Console says about both Show Siblings and Show Kerning Groups:
![screen shot 2016-05-02 at 6 41 20 pm](https://cloud.githubusercontent.com/assets/18740288/14970276/a07690de-1095-11e6-8c6a-b174a0cd801a.png)

And this is the message I'm seeing on Glyph's Macro Panel when I run the app:
![screen shot 2016-05-02 at 6 42 45 pm](https://cloud.githubusercontent.com/assets/18740288/14970299/d0245ef6-1095-11e6-872c-5f38b7d6e7e8.png)

Let me know if I can provide you with anything else.

Thanks again,
Jesen T.

**Comment by Mark2Mark** [comment]
I see. This looks pretty much like a problem with the Glyphs Version and the Plugin environment. I build everything in Glyphs 2.3. You are running a lower version?
Did the plugins still work for you very recently?

@schriftgestalt @mekkablue

**Comment by jtanadi** [comment]
Yes, I'm only on 2.2.2, which is what's available on their website. Is 2.3 beta?
I got the plugins only a few days ago and I haven't gotten them to work. I've never tried them with previous versions of Glyphs.

**Comment by Mark2Mark** [comment]
The stable Glyphs version 2.3 seems to be released in the next week. This will be the app update that renders all plugins working which are built on the new architecture. If you will then still have issues, please contact me.

**Comment by jtanadi** [comment]
Thanks Mark. I will download 2.3 when it's released and try your plug-ins again.

**Comment by jtanadi** [comment]
I want to confirm that the plug-ins are working great in 2.3. Thanks again!

**Comment by Mark2Mark** [comment]
Thank you for notifying. I was just going to ask you. You might have noticed the new Plugin Manager in Glyphs. It is now as easy as pie to get plugins (un)installed. I’ll add more in the next days.
